### ISSUE TITLE
Por que esse print não funciona?

### ISSUE THREAD

**Issue by mayconvs** [hansalemaos/raspagem_bet365_pe_de_cabra#1]
Por que quando eu dou esse print não funciona?
**print(allmems[0].regiondf.aa_dump_S1)**

```
from time import sleep
import regex as re
import sys, psutil, pymem, subprocess
import numpy as np
from pdmemedit import Pdmemory
from a_pandas_ex_sequence_search import pd_add_find_sequence
import pandas as pd

brave_nome_processo = "brave.exe"
brave_dir = r"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"
site_para_raspar = "https://www.bet365.com/#/IP/B1"

bravebro = subprocess.Popen(
    [
        brave_dir,
        site_para_raspar,
    ]
)
pd_add_find_sequence() # permite realizar operações que não são nativas do pandas, como a busca por sequências específicas de valores (por exemplo, bytes) em colunas de um DataFrame
allmapped = []
sleep(5)
allpids = []
allprocs = []

# Coleta todos os processos do Brave e adiciona em allprocs
for q in psutil.process_iter():
    try:
        if q.name() == brave_nome_processo:
            allprocs.append(q)
    except Exception:
        pass
    
    
resi = []
allmems = []
memmi = []
np8stuff = np.array([79, 68, 61], dtype=np.uint8)

# Cria um objeto Pdmemory para cada processo do Brave encontrado. Isso irá permitir a leitura e análise da memória
for q in allprocs:
    print("---------------------")
    allmems.append(Pdmemory(pid=q.pid, filename=None))
    
print(allmems[0].regiondf.aa_dump_S1)
```

Traceback (most recent call last):
  File "C:\wampPython\bot_pe_de_cabra\main.py", line 51, in <module>
    print((allmems[0].regiondf.aa_dump_S1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\wampPython\bot_pe_de_cabra\env\Lib\site-packages\pandas\core\generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**AttributeError: 'DataFrame' object has no attribute 'aa_dump_S1'**

Vi isso no vídeo https://www.youtube.com/watch?v=ZXuBccIVKbE

**Comment by hansalemaos** [comment]
Você não ativou o data type S1

**Comment by mayconvs** [comment]
> Você não ativou o data type S1

Mas como que eu ativo isso?
